INSERT INTO cliente(id,nome,cpf) VALUES(1,'Enrico Emanuel Souza','773.791.154-56');
INSERT INTO cliente(id,nome,cpf) VALUES(2,'Rafaela Ana Débora Jesus','451.720.308-59');
INSERT INTO cliente(id,nome,cpf) VALUES(3,'Nicole Mariane Daiane Moura','266.222.995-01');
INSERT INTO cliente(id,nome,cpf) VALUES(4,'José João Julio Lima','739.720.298-53');
INSERT INTO cliente(id,nome,cpf) VALUES(5,'João Gael Alves','582.401.742-56');
INSERT INTO cliente(id,nome,cpf) VALUES(6,'Valentina Carla Silvana da Costa','529.762.381-20');
INSERT INTO cliente(id,nome,cpf) VALUES(7,'Julio Geraldo Melo','446.205.378-88');
INSERT INTO cliente(id,nome,cpf) VALUES(8,'Hugo Davi Novaes','960.202.306-60');
INSERT INTO cliente(id,nome,cpf) VALUES(9,'Eliane Melissa Julia Dias','321.843.809-89');
INSERT INTO cliente(id,nome,cpf) VALUES(10,'José Fábio Ramos','916.024.314-77');
ALTER SEQUENCE cliente_id_seq RESTART WITH 11;

INSERT INTO produto(id,descricao,valor) VALUES (1,'Abajur [quebra-luz]','1102.37');
INSERT INTO produto(id,descricao,valor) VALUES (2,'Abraçadeiras de metal','603.63');
INSERT INTO produto(id,descricao,valor) VALUES (3,'Abridores de garrafas, elétricos e não-elétricos','2100.48');
INSERT INTO produto(id,descricao,valor) VALUES (4,'Bustos de madeira, cera, gesso ou plástico','2002.23');
INSERT INTO produto(id,descricao,valor) VALUES (5,'Buzinas grandes [trombetas]','1500.16');
INSERT INTO produto(id,descricao,valor) VALUES (6,'Cabideiros não metálicos','2000.80');
INSERT INTO produto(id,descricao,valor) VALUES (7,'Cabos de fibra óptica','906.66');
INSERT INTO produto(id,descricao,valor) VALUES (8,'Caixa para construção debaixo dágua','1900.42');
INSERT INTO produto(id,descricao,valor) VALUES (9,'Dispositivos economizadores de combustível para motores e máquinas','704.00');
INSERT INTO produto(id,descricao,valor) VALUES (10,'Dispositivos para almofadas de ar para deslocar cargas','1701.29');
INSERT INTO produto(id,descricao,valor) VALUES (11,'Eixos de transmissão para veículos terrestres','1202.46');
INSERT INTO produto(id,descricao,valor) VALUES (12,'Embalagens de papelão ou papel para garrafas ','1603.04');
INSERT INTO produto(id,descricao,valor) VALUES (13,'Fitas auto-adesivas, exceto para papelaria e uso medicinal ou doméstico','1700.92');
INSERT INTO produto(id,descricao,valor) VALUES (14,'Fixadores de esquis [calços de segurança]','2800.66');
INSERT INTO produto(id,descricao,valor) VALUES (15,'Flavorizantes, exceto óleos essenciais, para uso em cigarros eletrônicos','3400.43');
INSERT INTO produto(id,descricao,valor) VALUES (16,'Luvas para batedores [acessórios para jogos]','2800.15');
INSERT INTO produto(id,descricao,valor) VALUES (17,'Mochilas à tiracolo para transportar bebês','1800.44');
ALTER SEQUENCE produto_id_seq RESTART WITH 18;
